# Monitor settings
monitor = DP-1, highrr, auto, 1
monitor = DP-3, preferred, auto-left, 1.2

# Animations
$animationSpeed = 1
$easeInBezier = 0.12, 0, 0.39, 0
$easeOutBezier = 0.16, 1, 0.3, 1

# Colors
$primaryColor1 = rgba(ff75b5ff)
$primaryColor2 = rgba(db5c95ff)
$primaryColor3 = rgba(b34878ff)
$secondaryColor1 = rgba(b084ebff)
$secondaryColor2 = rgba(8c69c9ff)
$secondaryColor3 = rgba(6a4ca8ff)
$neutralColor1 = rgba(cdcdcdff)
$neutralColor2 = rgba(e6e6e6ff)
$neutralColor3 = rgba(757575ff)

# Visuals & Misc
$cursor = Bibata-Modern-Ice
$cursorSize = 28
$fontFamily = "Cantarell"
$gapsIn = 6
$gapsOut = 12
$borderSize = 4
$rounding = 8
$blurSize = 4
$allowTearing = true

# CURSOR FIX, $VARS DON'T WORK ?
env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,28
