# Defaults
$terminal = alacritty
# $terminal -e spf
$filemanager = thunar
$applauncher = fuzzel
$logoutmenu = nwg-bar
$idlehandler = swayidle -w timeout 300 'swaylock -f -c 000000' before-sleep 'swaylock -f -c 0>
$capturing = grim -g "$(slurp)" - | swappy -f -
$browser = flatpak run app.zen_browser.zen

# Environment variables
env = TERMINAL,alacritty
env = QT_QPA_PLATFORMTHEME,qt6ct
env = TZ,America/Argentina/Buenos_Aires

env = INPUT_METHOD, fcitx
# env = GTK_IM_MODULE, fcitx
env = QT_IM_MODULE, fcitx
env = XMODIFIERS, @im=fcitx
env = DefaultIMModule, fcitx
