input {
    repeat_rate = 35
    repeat_delay = 450
    accel_profile = flat
    scroll_factor = 1.5

    float_switch_override_focus = 2

    tablet {
        transform = 1
        output = current
    }
}
