$mainMod = SUPER
$sudoMod = SUPER_SHIFT
$ctrlMod = SUPER_CTRL
$commMod = SUPER_ALT

# Base
bind = $commMod, R, exec, eww reload & hyprctl reload & swaync-client --reload-config # killall waybar && waybar & disown
bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, SPACE, exec, $applauncher
bind = $sudoMod, SPACE, exec, $logoutmenu
bind = $mainMod, N, exec, swaync-client -t -sw
bind = $commMod, C, exec, cliphist list | fuzzel --dmenu | cliphist decode | wl-copy

# Misc
bind = $mainMod, S, exec, $capturing

# Applications
bind = $mainMod, E, exec, $filemanager
bind = $mainMod, W, exec, $browser

# Window & layout manipulation
bind = $mainMod, C, killactive
bind = $sudoMod, C, exec, hyprctl kill
bind = $mainMod, F, fullscreen, 1
bind = $sudoMod, F, fullscreen
bind = $ctrlMod, F, togglefloating

bindm = $mainMod, mouse:272, movewindow
binde = $mainMod, left, movefocus, l
binde = $ctrlMod, left, movewindow, l
binde = $mainMod, right, movefocus, r
binde = $ctrlMod, right, movewindow, r
binde = $mainMod, up, movefocus, u
binde = $ctrlMod, up, movewindow, u
binde = $mainMod, down, movefocus, d
binde = $ctrlMod, down, movewindow, d

bind = $mainMod, G, togglegroup
binde = ALT, Tab, changegroupactive, f
bind = $mainMod, L, togglesplit

bindm = $mainMod, mouse:273, resizewindowrr
$resizePx = 20
bind = $mainMod, R, submap, Resize
submap = Resize
binde = , right, resizeactive, $resizePx 0
binde = , left, resizeactive, -$resizePx 0
binde = , up, resizeactive, 0 -$resizePx
binde = , down, resizeactive, 0 $resizePx
bind = , catchall, submap, reset
submap = reset

# TODO: Special workspace
# bindd = $mainMod, minus, Move active window to Special workspace, movetoworkspace,special
# bindd = $mainMod, equal, Toggles the Special workspace, togglespecialworkspace, special
# bindd = $mainMod, F1, Call special workspace scratchpad, togglespecialworkspace, scratchpad
# bindd = $mainMod ALT SHIFT, F1, Move active window to special workspace scratchpad, movetoworkspacesilent, special:scratchpad

# Workspace manipulation
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1
bind = $sudoMod $ctrlMod, left, movetoworkspace, -1
bind = $sudoMod $ctrlMod, right, movetoworkspace, +1
bind = $sudoMod, left, workspace, -1
bind = $sudoMod, right, workspace, +1
bind = $mainMod, slash, workspace, previous

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

# Default controllers
binde = , XF86AudioLowerVolume, exec, pamixer -ud 3 && pamixer --get-volume > /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob
binde = , XF86AudioRaiseVolume, exec, pamixer -ui 3 && pamixer --get-volume > /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob
bind = , XF86AudioMute, exec, amixer sset Master toggle | sed -En '/\[on\]/ s/.*\[([0-9]+)%\].*/\1/ p; /\[off\]/ s/.*/0/p' | head -1 > />
bind = , XF86AudioPlay, exec, playerctl play-pause
bind = , XF86AudioNext, exec, playerctl next
bind = , XF86AudioPrev, exec, playerctl previous
binde = , XF86MonBrightnessUp, exec, brightnessctl s +5%
binde = , XF86MonBrightnessDown, exec, brightnessctl s 5%-
