# TO SEE ACTIVE CLASSES: hyprctl clients | grep 'initialClass: '

# XWayland detection (changes active border to yellow)
windowrulev2 = bordercolor rgb(FFB86C), xwayland:1

# Rules
windowrulev2 = float, initialClass:blueman-manager
windowrulev2 = float, initialclass:org.pulseaudio.pavucontrol
windowrulev2 = float, initialclass:piper
windowrulev2 = float, initialClass:git-cola
# windowrulev2 = size 80% 80%, class:^(git-cola)$
# windowrulev2 = float, class:^(qt5ct|qt6ct|kvantummanager|nwg-look)

# Blueman size fix
windowrulev2 = size 25% 25%, initialclass:blueman-manager

# Layers
# layerrule = blur,waybar
# layerrule = blur,Fuzzel
# layerrule = blur,logout_dialog
# Layers Rules End #

# Base
windowrulev2 = float, class:^(xdg-desktop-portal-gtk|xdg-desktop-portal-kde|xdg-desktop-portal-hyprland)(.*)$
windowrulev2 = float, title:^(MainPicker)$
windowrulev2 = float, title:^(Picture-in-Picture)$
windowrulev2 = size 960 540, title:^(Picture-in-Picture)$
windowrulev2 = move 25%-, title:^(Picture-in-Picture)$
